#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT_split_3x6_3(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ESC, KC_LCTL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_QUOT, KC_LGUI, MO(2), KC_SPC, KC_ENT, MO(1), KC_RALT),
                                                              [1] = LAYOUT_split_3x6_3(KC_TAB, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_LSFT, LCTL(KC_LSFT), KC_PSCR, KC_DEL, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_NO, KC_LCTL, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LGUI, MO(3), KC_SPC, KC_ENT, KC_TRNS, KC_RALT),
                                                              [2] = LAYOUT_split_3x6_3(KC_TAB, KC_QUOT, KC_LT, KC_GT, KC_DQUO, KC_DOT, KC_AMPR, KC_UNDS, KC_LBRC, KC_RBRC, KC_PERC, KC_BSPC, KC_LSFT, KC_EXLM, KC_MINS, KC_PLUS, KC_EQL, KC_HASH, KC_PIPE, KC_COLN, KC_LPRN, KC_RPRN, KC_QUES, KC_GRV, KC_LCTL, KC_CIRC, KC_SLSH, KC_ASTR, KC_BSLS, KC_NO, KC_TILD, KC_DLR, KC_LCBR, KC_RCBR, KC_AT, KC_NO, KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, MO(3), KC_RALT),
                                                              [3] = LAYOUT_split_3x6_3(QK_BOOT, KC_NO, KC_NO, KC_NO, RGB_VAD, RGB_VAI, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, KC_BSPC, KC_LSFT, KC_LALT, RGB_VAD, RGB_VAI, RGB_SAD, RGB_SAI, KC_F5, KC_F6, KC_F7, KC_F8, KC_NO, KC_NO, KC_LCTL, RGB_TOG, RGB_RMOD, RGB_MOD, RGB_HUD, RGB_HUI, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO, KC_LGUI, KC_TRNS, KC_SPC, KC_ENT, KC_TRNS, KC_RALT)};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

#ifdef OLED_ENABLE
enum LAYERS { LAYER_0, LAYER_1, LAYER_2, LAYER_3 };

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (!is_keyboard_master()) return OLED_ROTATION_270; // flips the display 180 degrees if offhand

    return OLED_ROTATION_270; // normal display
}

void write_layer_state(void) {
    int  highest_layer    = get_highest_layer(layer_state);
    bool is_shift_pressed = (get_mods() & MOD_MASK_SHIFT) != 0;

    switch (highest_layer) {
        case LAYER_0:
            if (is_shift_pressed)
                oled_write("QWERTASDFGZXCVB", false);
            else
                oled_write("qwertasdfgzxcvb", false);

            break;
        case LAYER_1:
            if (is_shift_pressed)
                oled_write("!@#$%          ", false);
            else
                oled_write("12345          ", false);

            break;
        case LAYER_2:
            if (is_shift_pressed)
                oled_write("\"<>\">!_++#^?*| ", false);
            else
                oled_write("'<>\".!-+=#^/*\\ ", false);
            break;
        case LAYER_3:
            oled_write("               ", false);
            break;
        default:
            oled_write("Unknown", false);
            break;
    }
}

void write_slave_layer_state(void) {
    int  highest_layer    = get_highest_layer(layer_state);
    bool is_shift_pressed = (get_mods() & MOD_MASK_SHIFT) != 0;

    switch (highest_layer) {
        case LAYER_0:
            if (is_shift_pressed)
                oled_write("YUIOPHJKL:NM<>?", false);
            else
                oled_write("yuiophjkl;nm,./", false);

            break;
        case LAYER_1:
            static const char PROGMEM ARROWS[] = {27, 25, 24, 26, '\0'};
            if (is_shift_pressed) {
                oled_write("^&*()", false);
                oled_write_P(ARROWS, false);
                oled_write("      ", false);
            } else {
                oled_write("67890", false);
                oled_write_P(ARROWS, false);
                oled_write("      ", false);
            }

            break;
        case LAYER_2:
            if (is_shift_pressed)
                oled_write("&_{}%|:()?~${}@", false);
            else
                oled_write("&_[]%|:()?~${}@", false);
            break;
        case LAYER_3:
            oled_write("               ", false);
            break;
        default:
            oled_write("Unknown", false);
            break;
    }
}

void write_wpm(void) {
    oled_write(" ", false);
    oled_write(get_u8_str(get_current_wpm(), '0'), false);
    oled_write(" ", false);
}

void write_spacer(void) {
    oled_write("     ", false);
}

void write_current_layer(void) {
    static const char *layer_names[] = {"QWERT", "NUMB ", "SYMBL", "FUNC ", "UNKN "};
    oled_write("LYR: ", false);
    int highest_layer = get_highest_layer(layer_state);
    oled_write(layer_names[highest_layer < 4 ? highest_layer : 4], false);
}

void write_boolean(bool value) {
    static const char PROGMEM TRUE[]  = {7, 0};
    static const char PROGMEM FALSE[] = {9, 0};
    if (value)
        oled_write_P(TRUE, false);
    else
        oled_write_P(FALSE, false);
}

void write_led_states(void) {
    led_t led_state = host_keyboard_led_state();

    oled_write("NUM:", false);
    write_boolean(led_state.num_lock);

    oled_write("CAP:", false);
    write_boolean(led_state.caps_lock);

    oled_write("SCR:", false);
    write_boolean(led_state.scroll_lock);
}

void write_penguin(void) {
    static const char PROGMEM PENGUIN[] = {0x20, 0x99, 0x9A, 0x20, 0x20, 0x20, 0xB9, 0xBA, 0x20, 0x20, '\0'};
    oled_write_P(PENGUIN, false);
}

void write_name(void) {
    static const char PROGMEM NAME[] = {213, 214, 215, 216, 217, '\0'};
    oled_write_P(NAME, false);
}

void write_wpm_bar(void) {
    static const char PROGMEM BLOCK_CHAR[] = {164, '\0'};
    static const char PROGMEM EMPTY_CHAR[] = {32, '\0'};

    int wpm                  = get_current_wpm();
    int wpm_bar_length       = (wpm * 5) / 100;
    wpm_bar_length           = wpm_bar_length > 5 ? 5 : wpm_bar_length;
    int wpm_bar_empty_length = 5 - wpm_bar_length;

    for (int i = 0; i < wpm_bar_length; i++) {
        oled_write_P(BLOCK_CHAR, false);
    }
    for (int i = 0; i < wpm_bar_empty_length; i++) {
        oled_write_P(EMPTY_CHAR, false);
    }
}

void slave_oled_task(void) {
    oled_set_cursor(0, 0);
    write_slave_layer_state();
    write_spacer();
    write_spacer();
    write_spacer();
    oled_write("WPM: ", false);
    write_wpm();
    write_spacer();
    write_current_layer();
    write_spacer();
    write_spacer();
    write_spacer();
    write_wpm_bar();
}

void master_oled_task(void) {
    oled_set_cursor(0, 0);
    write_layer_state();
    write_spacer();
    write_led_states();
    write_spacer();
    write_spacer();
    write_spacer();
    write_penguin();
    write_spacer();
    write_spacer();
    write_name();
}

bool oled_task_user(void) {
    if (is_keyboard_master())
        master_oled_task();
    else
        slave_oled_task();

    return false;
}

#endif // OLED_ENABLE
